config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: {maximum: 20}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 127},
                                    format: { with: VALID_EMAIL_REGEX },
                                    uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: {minimum: 6, maximum: 20}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash[:danger] = 'メールアドレスかパスワードが間違っています' 
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :logged_in_user, only: [:index, :destroy]
   before_action :admin_user,     only: :destroy
  
  
    def index
      @users = User.paginate(page: params[:page])
    end
    
    def show
      @user = User.find(params[:id])
    end
    
    def new
      @user = User.new
    end
    
    def create
      @user = User.new(user_params)
      if @user.save
        log_in @user
        flash[:success] = "登録が完了しました"
        redirect_to @user
      else
        render 'new'
      end
    end
    
    def destroy
      User.find(params[:id]).destroy
      flash[:success] = "ユーザーを削除しました"
      redirect_to users_url
    end
  
  private
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
    
    def logged_in_user
      unless logged_in?
        flash[:danger] = "ログインしてください"
        redirect_to login_url
      end
    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def full_title(page_title = '')
    base_title = "Spotify Music App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
  <div class="container header-list">
      <h1><%= link_to "Spotify Music Review App", root_path, id: "logo" %></h1>
      <ul class="header-list-ul">
         <li class="btn"><%= link_to "アカウント作成", signup_path %></li>
         <% if logged_in? %>
              <li><%= link_to "参加ユーザー", users_path %></li>
              <li><%= link_to "プロフィール", current_user %></li>
              <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
         <% else %>
             <li class="btn"><%= link_to "ログイン", login_path %></li>
         <% end %>
        <li class="btn"><%= link_to "このアプリについて", about_path %></li>
      </ul>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta-charset="utf-8">
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <section class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </section>
  </body>
  <footer>
    
  </footer>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="about">
  <p>APIを使いたいと思い作り始めました。</p>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="home">
  <h2>Spotify Music Review App</h2>
  <p>Spotify API を用いたアプリです。気になるレビューがされている音楽をすぐに聴くことが出来ます。</p>
</div>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "削除", user, method: :delete,
                                  data: { confirm: "このユーザーを削除します" } %>
  <% end %>
</li>

app/views/users/index.html.erb
<% provide(:title, 'ユーザー') %>
<h1>参加ユーザー</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, "新規作成") %>
<div class="signup">
  <h1>アカウント作成</h1>
  <div class="sign-up-form">
    <%= form_for(@user) do |f| %>
          <%= render 'shared/error_messages' %>
          
          <%= f.label :name, "名前" %>
          <%= f.text_field :name, class: 'form-control' %>
    
          <%= f.label :email, "メールアドレス" %>
          <%= f.email_field :email, class: 'form-control' %>
    
          <%= f.label :password, "パスワード(6~20文字)" %>
          <%= f.password_field :password, class: 'form-control' %>
    
          <%= f.label :password_confirmation, "パスワード確認" %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
    
          <%= f.submit "アカウント作成", class: "btn" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  
</div>